config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks do
    # /tasks/new/confirmにきたらconfirm_newアクションを実行
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  #imageを紐づける
  has_one_attached :image
  validates :name, presence: true, length: { maximum: 30 }
  # カスタムしたバリデーションの場合はvalidateメソッドを用いる
  validate  :validate_name_not_including_comma

  belongs_to :user

  # DBへのクエリ用メソッドのショートカットを作成することができる
  # current_user.tasks.recent で現在のユーザのタスクを降順で取得 
  scope :recent, -> { order(created_at: :desc)}

  def self.ransackable_attributes(auth_object = nil)
    ["name", "created_at"] 
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  # どの属性をどの順番で出力するのかを定義
  def self.csv_attributes
    # %w[ name, description, created_at, updated_at ]
    ["name", "description", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      #一行目としてヘッダーを出力
      csv << csv_attributes
      #allメソッドで全タスクを取得し、１レコードずつCSVとして出力
      all.each do |task|
        csv << csv_attributes.map{|attr| task.send(attr) }
      end
    end
  end
  
  def self.import(file)
    # foreachメソッドで一行ずつ読み込み
    CSV.foreach(file.path, headers: true) do |row|
      # classに対してimportが直接呼ばれる場合はTask.newと同義になる
      task = new
      # to_hashメソッドより、csvの各カラムをハッシュ形式に変換、CSVのヘッダー情報をからデータベースに登録するため
      # 意図しないデータの登録を避けるためsliceに配列を渡して登録予定のカラムの情報のみを登録できるようにフィルタリングする
      task.attributes = row.to_hash.slice(*csv_attributes)
      # データベースに登録
      task.save!
    end
  end

  private
  
  def validate_name_not_including_comma
    # nameがnilでもエラーにならない
    errors.add(:name, 'にカンマを含めることはできません。') if name&.include?(',')
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  def new
    @user = User.new(flash[:user])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      redirect_back fallback_location: @user, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
      }
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redire_to admin_user_path(@user), notice: "ユーザ「#{user.name}」を登録しました。"
    else
      redirect_back fallback_location: @user, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
      }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_path, status: :see_other, notice: "ユーザ「#{@user.name}」を削除しました。"
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_comfirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required


  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # どのURLにアクセスしてもログインが必要となりリダイレクトされるのを防ぐため
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      # binding.pry
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new 
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: %i[ show edit update destroy ]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distint: true).page(params[:page])

    # アクセスしてきたURLによってレスポンスを切り替える
    respond_to do |format|
      format.html
      # csvでアクセスしてきた場合にcsvファイルを返す
      format.csv { send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def show

  end

  def new
    @task = Task.new(flash[:task])
  end

  def create
    @task = current_user.tasks.new(task_params) 

    if params[:back].present?
      render :new
      return
    end

    if @task.save
      # mail 送信 (利用する時は起動後にコンテナにgem mailcatcherをinstall)
      # TaskMailer.creation_email(@task).deliver_now
      SampleJob.perform_later
      flash[:notice] = "タスク名:#{@task.name}を登録しました。"
      redirect_to tasks_path(:task)
      # redirect_to tasks_path, notice: "タスク名:#{task.name}を登録しました。"
    else
      redirect_back fallback_location: new_task_path, flash: {
        task: @task,
        error_messages: @task.errors.full_messages
      }
    end
  end
  
  def edit
  
  end

  def update
    task = current_user.tasks.find(params[:id])
    if task.update(task_params)
      redirect_to tasks_url, notice: "タスク「#{task.name}」を更新しました。"
    else
      redirect_back fallback_location: edit_task_path, flash: {
        task: task,
        error_messages: task.errors.full_messages
      }
    end
  end

  def destroy
    @task.destroy
    head :no_content
    # redirect_to tasks_url, status: :see_other, notice: "タスク「#{@task.name}」を削除しました。"
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render new_task_path unless @task.valid?
  end

  def import
    current_user.tasks.import(params[:file])
    redirect_to tasks_url, notice: "タスクを追加しました"
  end

  private
  def task_params
    params.require(:task).permit(:name, :description, :image)
  end

  def set_tasks
    @task = current_user.tasks.find(params[:id]) 
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.erb
<%= render partial: 'share/error_message'%>

<%= form_with model: [:admin, @user], local: true do |f| %>
  <div class='form-group'>
     <%=  f.label :name, '名前' %>
     <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
     <%=  f.label :email, 'メールアドレス' %>
     <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class='form-check'>
     <%=  f.label :admin, class: 'form-check-label' do %>
        <%= f.check_box :admin, class: 'form-check-inputs' %>
        管理者権限
     <% end %>
  </div>
  <div class='form-group'>
     <%=  f.label :password, 'パスワード' %>
     <%= f.text_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
     <%=  f.label :password_confirmation, 'パスワード確認' %>
     <%= f.text_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn btn-secondary' %>

<% end %>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集</h1>
<div class="nav justify-content-end">
  <%= link_to, '一覧', admin_users_path, class: 'nav-link' %>
</div>
<%= render partial: 'form', locals: { user: @user} %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= link_to '新規登録', new_admin_user_path, class: 'btn btn-secondary' %>

<div class='mb-3'>
  <table class='table table-hover'>
    <thead class="thead-defalut">
      <tr>
        <th><%= User.human_attribute_name(:name)%></th>
        <th><%= User.human_attribute_name(:email)%></th>
        <th><%= User.human_attribute_name(:admin)%></th>
        <th><%= User.human_attribute_name(:created_at)%></th>
        <th><%= User.human_attribute_name(:updated_at)%></th>
        <th></th>
      </tr>
    </thead> 
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, [:admin, user] %></td>
          <td><%= user.email %></td>
          <td><%= user.admin? ? 'あり' : 'なし'%></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
          <td>
            <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-secondary mr-3'%>
            <%= link_to '削除', [:admin, user], data: { turbo_method: 'delete', turbo_comfirm: "ユーザ「#{user.name}」を削除してもよろしいですか？"}, class: 'btn btn-secondary mr-3' %>
          </td>
        </tr>
      <% end %>
    </tbody>
</div>

app/views/admin/users/new.html.erb
<h1>ユーザー登録</h1>
<div class="nav justify-content-end">
  <%= link_to '一覧', admin_users_path, class: 'nav-link' %>
</div>
<%= render partial: 'form', locals: { user: @user} %>

app/views/admin/users/show.html.erb
<h1>ユーザの詳細</h1>
<div class="nav justify-content-end">
  <%= link_to '一覧', admin_users_path, class: 'nav-link' %> 
</div>
<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= User.human_attribute_name(:id) %></th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:email) %></th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:admin) %></th>
      <td><%= @user.admin? ? 'あり' : 'なし'%></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:created_at) %></th>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:updated_at) %></th>
      <td><%= @user.updated_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_admin_user_path, class: 'btn btn-secondary mr-3'%>
<%= link_to '削除', [:admin, @user], data: { turbo_method: "delete", turbo_comfirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"} %>

app/views/application/_header.html.erb
<nav class="navbar bg-secondary-subtle">
  <div class="container-fluid">
    <%= link_to 'Taskleaf', tasks_path, class: 'navbar-brand'%>
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item"><%= link_to 'タスク一覧', tasks_path, class: 'nav-link' %></li>
        <% if current_user.admin? %>
          <li class="nav-item"><%= link_to 'ユーザ一覧', admin_users_path, class: 'nav-link' %></li>
        <% end %>
        <li class="nav-item"><%= link_to 'ログアウト', logout_path, data: {turbo_method: 'delete'}, class: 'nav-link' %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'application/header'%>
    <div class='container'> 
      <% if flash[:notice] %>
        <div class='alert alert-primary'>
          <%= flash[:notice] %> 
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/share/_error_message.html.erb
<% if flash[:error_messages] %>
  <ul class='alert alert-danger' id='error_explanation'>
    <% flash[:error_messages].each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/_form.html.erb
<%= render partial: 'share/error_message'%>

<%= form_with model: task do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', id: 'task_name' %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5, class: 'form-control', id: 'task_description' %>
  </div>
  <div class='form-group'>
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <%= f.submit nil, class: 'btn btn-secondary' %>

<% end %>

app/views/tasks/confirm_new.html.erb
<h1>登録内容の確認</h1>

<%= form_with model: @task, data: { turbo: false } do |f| %>
  <table class="table table-hover">
    <tbody>
      <tr>
        <th><%= Task.human_attribute_name(:name) %></th>
        <td>
          <%= @task.name %>
          <%= f.hidden_field :name %>
        </td>
      </tr>
      <tr>
        <th><%= Task.human_attribute_name(:description) %></th>
        <td>
          <%= simple_format(@task.description) %>
          <%= f.hidden_field :description %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3' %>
  <%= f.submit '登録', class: 'btn btn-secondary' %>

<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>
<div class='nav justify-content-end'>
  <%= link_to '一覧', tasks_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { task: @task } %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= search_form_for @q, class: 'mb-5' do |f| %>
 <div class="form-group row">
   <%= f.label :name_cont, '名前', class: 'col-sm-2 col-form-label' %>   
   <div class="col-sm-10">
     <%= f.search_field :name_cont, class: 'form-control' %>
   </div>
 </div>
 <div class="form-group row">
   <%# _gteq: greater than or equal %>
   <%= f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label' %>
   <div class="col-sm-10">
     <%= f.search_field :created_at_gteq, class: 'form-control' %>
   </div>
 </div>
 <div class="form-group">
   <%= f.submit class: 'btn btn-outline-primary' %>
 </div>
<% end %>

<div class="mb-3">
  <%= paginate @tasks %>
  <%= page_entries_info @tasks %>
</div>

<%= link_to "新規作成", new_task_path, class: 'btn btn-primary' %>

<div class='mb-3'>
  <table class='table table-hover'>
    <thead class='thead-defalut'>
      <tr>
        <th><%= sort_link(@q, :name) %></th> 
        <th><%= Task.human_attribute_name(:created_at)%></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task|%>
        <tr>
          <td><%= link_to task.name, task %>
          <td><%= task.created_at %>
          <td>
            <%= link_to '編集', task, class: 'btn btn-secondary mr-3' %>
            <%= link_to '削除', task, class: 'btn btn-secondary delete',  data: { turbo_method: :delete, turbo_confirm: '削除してもよろしいですか？' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'エスクポート', tasks_path(format: :csv), class: 'btn btn-secondary' %>

<%= form_with url: import_tasks_path, multipart: true, class: 'mb-3' do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート", class: 'btn btn-secondary' %>
<% end %>

app/views/tasks/new.html.erb
<h1>タスクの新規作成</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧', tasks_path, class: 'nav-link'%>
</div>
<%= render partial: 'share/error_message' %>

<%= render partial: 'form', locals: { task: @task } %>

<%
=begin
%>
画像を添付する際に確認画面を挟むと少し設定が必要にある
今回は確認画面を実施しない状況で作成(速習ガイド)
<%= form_with model: @task, url: confirm_new_task_path, data: { turbo: false } do |f| %>
  <div class="form-group">
    <%= f.label :name  %>
    <%= f.text_field :name, class: 'form-control', id: 'task_name' %>
  </div>
  <div class="form-group">
    <%= f.label :description  %>
    <%= f.text_area :description, rows: 5, class: 'form-control', id: 'task_description' %>
  </div>
  <%= f.submit '確認', class: 'btn btn-secondary' %>

<% end %>  
<% 
=end
%>

app/views/tasks/show.html.erb
<h1>タスクの詳細</h1>

<div class='nav justify-content-end'>
  <%= link_to '一覧', tasks_path, class: 'nav-link' %>
</div>
<table class='table table-hover'>
  <tbody>
    <tr>
      <th><%= Task.human_attribute_name(:id)%></th>
      <td><%= @task.id %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:name) %></th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:description) %></th>
      <td><%= auto_link(simple_format(h(@task.description), {}, sanitaize: false, wrapper_tag: "div")) %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:image) %></th>
      <%# image_tagはイメージが添付しているかどうかに関わらず存在し、存在しない場合エラーとなるため条件分岐している%>
      <td><%= image_tag @task.image if @task.image.attached? %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:updated_at) %></th>
      <td><%= @task.updated_at %></td>
    </tr>
  </tbody>

</table>
<%= link_to '編集', edit_task_path, class: 'btn btn-secondary mr-3' %>
<%= link_to '削除', @task, data: { turbo_method: :delete, turbo_confirm: '削除してもよろしいでしょうか？'},class: 'btn btn-secondary mr-3' %>